/**
 * KBoxAuthSheet - Bottom sheet to collect the KBox API key.
 *
 * The key is generated by the owner in the KBox web UI (Settings →
 * System → API Access) and grants LED/fan/power control, so it's
 * treated like a password: stored in expo-secure-store only.
 *
 * Unlike AvalonAuthSheet (where the parent verifies), this sheet
 * verifies the key itself with a GET /api/v1/status round-trip and
 * persists **only on success** — a bad key never overwrites a stored
 * good one, and a stale stored key stays as prefill after the owner
 * regenerates it on the device.
 */

import { useState, useCallback, useEffect } from 'react';
import { View, Pressable, TextInput, ActivityIndicator } from 'react-native';
import { Ionicons } from '@expo/vector-icons';
import { Sheet } from '../Sheet';
import { Text } from '../Text';
import { haptics } from '@/utils/haptics';
import { colors } from '@/constants/colors';
import { useTranslation } from '@/i18n';
import { kbox, isSuccess } from '@/api';
import { getKBoxApiKey, setKBoxApiKey } from '@/utils/kboxAuth';

export interface KBoxAuthSheetProps {
  visible: boolean;
  ip: string;
  /** Called after the key verified against the device and was stored */
  onSuccess: () => void;
  onClose: () => void;
}

export function KBoxAuthSheet({
  visible,
  ip,
  onSuccess,
  onClose,
}: KBoxAuthSheetProps) {
  const { t } = useTranslation();
  const [apiKey, setApiKey] = useState('');
  const [revealed, setRevealed] = useState(false);
  const [verifying, setVerifying] = useState(false);
  const [error, setError] = useState<string | null>(null);

  // Pre-fill with the stored key (if any) when the sheet opens; reset on close.
  useEffect(() => {
    if (visible) {
      void (async () => {
        const stored = await getKBoxApiKey(ip);
        if (stored) setApiKey(stored);
      })();
    } else {
      setApiKey('');
      setRevealed(false);
      setVerifying(false);
      setError(null);
    }
  }, [visible, ip]);

  const handleSubmit = useCallback(async () => {
    const trimmed = apiKey.trim();
    if (!trimmed || verifying) return;
    haptics.light();
    setVerifying(true);
    setError(null);

    const result = await kbox.getStatus(ip, trimmed);
    const errorCode = isSuccess(result)
      ? result.data.ok === false
        ? (result.data.error ?? 'unknown')
        : null
      : (result.error.code ?? 'unknown');

    if (errorCode === null) {
      await setKBoxApiKey(ip, trimmed);
      haptics.success();
      setVerifying(false);
      onSuccess();
      onClose();
      return;
    }

    setVerifying(false);
    haptics.error();
    if (errorCode === 'unauthorized') {
      setError(t('errors.kboxUnauthorized'));
    } else if (errorCode === 'api_disabled') {
      setError(t('errors.kboxApiDisabled'));
    } else {
      setError(t('errors.kboxVerifyFailed'));
    }
  }, [apiKey, verifying, ip, onSuccess, onClose, t]);

  return (
    <Sheet visible={visible} onClose={onClose} avoidKeyboard>
      <View className="flex-row items-center justify-between pb-4">
        <Text variant="subtitle" className="font-semibold">
          {t('miners.kboxApiKeyTitle')}
        </Text>
        <Pressable onPress={onClose} className="p-2 -mr-2" hitSlop={8}>
          <Ionicons name="close" size={24} color={colors.text} />
        </Pressable>
      </View>

      <Text variant="caption" color="muted" className="mb-4">
        {t('miners.kboxApiKeyHint')}
      </Text>

      <View className="flex-row items-center bg-background rounded-lg border border-border">
        <TextInput
          value={apiKey}
          onChangeText={(v) => {
            setApiKey(v);
            setError(null);
          }}
          placeholder={t('miners.kboxApiKeyPlaceholder')}
          placeholderTextColor={colors.textMuted}
          secureTextEntry={!revealed}
          style={{
            flex: 1,
            paddingHorizontal: 16,
            paddingVertical: 12,
            color: colors.text,
            fontSize: 14,
            fontFamily: 'JetBrainsMono_400Regular',
          }}
          autoFocus
          maxLength={64}
          autoCapitalize="none"
          autoCorrect={false}
          returnKeyType="done"
          onSubmitEditing={handleSubmit}
          editable={!verifying}
        />
        <Pressable
          onPress={() => setRevealed((v) => !v)}
          className="p-3"
          hitSlop={8}
        >
          <Ionicons
            name={revealed ? 'eye-off' : 'eye'}
            size={20}
            color={colors.textMuted}
          />
        </Pressable>
      </View>

      {error && (
        <Text
          variant="caption"
          className="mt-2"
          style={{ color: colors.danger }}
        >
          {error}
        </Text>
      )}

      <View className="flex-row gap-3 mt-6">
        <Pressable
          onPress={onClose}
          disabled={verifying}
          className="flex-1 py-3 rounded-lg bg-background border border-border items-center"
          style={({ pressed }) => ({ opacity: pressed || verifying ? 0.7 : 1 })}
        >
          <Text variant="body" className="font-medium">
            {t('common.cancel')}
          </Text>
        </Pressable>
        <Pressable
          onPress={handleSubmit}
          disabled={apiKey.trim().length === 0 || verifying}
          className="flex-1 py-3 rounded-lg bg-foreground items-center"
          style={({ pressed }) => ({
            opacity: pressed || apiKey.trim().length === 0 ? 0.5 : 1,
          })}
        >
          {verifying ? (
            <ActivityIndicator size="small" color={colors.background} />
          ) : (
            <Text variant="body" className="font-medium text-gray-950">
              {t('common.save')}
            </Text>
          )}
        </Pressable>
      </View>
    </Sheet>
  );
}
